name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Go Env
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Run unit test
        working-directory: ./
        run: |
          make unit-test

